CREATE TABLE IF NOT EXISTS products (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code VARCHAR(40) NOT NULL UNIQUE,
 name VARCHAR(120) NOT NULL, description VARCHAR(500), tenure_type VARCHAR(20) NOT NULL,
 min_tenure_value INT NOT NULL, max_tenure_value INT NOT NULL, interest_rate DECIMAL(9,4) NOT NULL,
 loan_structure_type VARCHAR(20) NOT NULL, installment_count INT, billing_cycle_type VARCHAR(30) NOT NULL,
 active BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL,
 CONSTRAINT ck_products_tenure CHECK (min_tenure_value > 0 AND max_tenure_value >= min_tenure_value)
);
CREATE TABLE IF NOT EXISTS fees (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id BIGINT NOT NULL,
 fee_category VARCHAR(20) NOT NULL, calculation_type VARCHAR(20) NOT NULL, application_timing VARCHAR(30) NOT NULL,
 amount DECIMAL(19,4) NOT NULL, days_after_due INT, active BOOLEAN NOT NULL,
 CONSTRAINT fk_fees_product FOREIGN KEY(product_id) REFERENCES products(id),
 CONSTRAINT ck_fees_amount CHECK(amount >= 0), CONSTRAINT ck_fees_days CHECK(days_after_due IS NULL OR days_after_due >= 0)
);
CREATE TABLE IF NOT EXISTS customers (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, first_name VARCHAR(80) NOT NULL, last_name VARCHAR(80) NOT NULL,
 email VARCHAR(150) NOT NULL UNIQUE, phone VARCHAR(30) NOT NULL UNIQUE, national_id VARCHAR(40) NOT NULL UNIQUE,
 address VARCHAR(250), customer_segment VARCHAR(40), preferred_channel VARCHAR(20) NOT NULL,
 billing_cycle_type VARCHAR(30) NOT NULL, billing_day INT, active BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL,
 CONSTRAINT ck_customers_billing_day CHECK(billing_day IS NULL OR billing_day BETWEEN 1 AND 31)
);
CREATE TABLE IF NOT EXISTS loan_limits (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id BIGINT NOT NULL UNIQUE,
 max_limit DECIMAL(19,4) NOT NULL, available_limit DECIMAL(19,4) NOT NULL, risk_tier VARCHAR(20),
 updated_at TIMESTAMP NOT NULL, version BIGINT NOT NULL,
 CONSTRAINT fk_limits_customer FOREIGN KEY(customer_id) REFERENCES customers(id),
 CONSTRAINT ck_limits_values CHECK(max_limit >= 0 AND available_limit >= 0 AND available_limit <= max_limit)
);
CREATE TABLE IF NOT EXISTS loans (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, loan_number VARCHAR(40) NOT NULL UNIQUE,
 customer_id BIGINT NOT NULL, product_id BIGINT NOT NULL, principal_amount DECIMAL(19,4) NOT NULL,
 interest_rate DECIMAL(9,4) NOT NULL, tenure_value INT NOT NULL, loan_structure_type VARCHAR(20) NOT NULL,
 billing_cycle_type VARCHAR(30) NOT NULL, state VARCHAR(20) NOT NULL, disbursement_date DATE, due_date DATE,
 outstanding_principal DECIMAL(19,4) NOT NULL, outstanding_fees DECIMAL(19,4) NOT NULL,
 created_at TIMESTAMP NOT NULL, closed_at TIMESTAMP,
 CONSTRAINT fk_loans_customer FOREIGN KEY(customer_id) REFERENCES customers(id), CONSTRAINT fk_loans_product FOREIGN KEY(product_id) REFERENCES products(id),
 CONSTRAINT ck_loans_amounts CHECK(principal_amount > 0 AND outstanding_principal >= 0 AND outstanding_fees >= 0)
);
CREATE INDEX IF NOT EXISTS ix_loans_customer_state ON loans(customer_id,state);
CREATE TABLE IF NOT EXISTS installments (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, loan_id BIGINT NOT NULL, installment_number INT NOT NULL,
 due_date DATE NOT NULL, principal_due DECIMAL(19,4) NOT NULL, fees_due DECIMAL(19,4) NOT NULL,
 amount_paid DECIMAL(19,4) NOT NULL, fees_paid DECIMAL(19,4) NOT NULL, state VARCHAR(20) NOT NULL,
 CONSTRAINT fk_installments_loan FOREIGN KEY(loan_id) REFERENCES loans(id), CONSTRAINT uq_installment_no UNIQUE(loan_id,installment_number)
);
CREATE TABLE IF NOT EXISTS loan_charges (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, loan_id BIGINT NOT NULL, installment_id BIGINT,
 fee_configuration_id BIGINT, fee_category VARCHAR(20) NOT NULL, amount DECIMAL(19,4) NOT NULL,
 applied_date DATE NOT NULL, description VARCHAR(250), deduplication_key VARCHAR(180) NOT NULL UNIQUE,
 CONSTRAINT fk_charges_loan FOREIGN KEY(loan_id) REFERENCES loans(id), CONSTRAINT fk_charges_installment FOREIGN KEY(installment_id) REFERENCES installments(id), CONSTRAINT fk_charges_fee FOREIGN KEY(fee_configuration_id) REFERENCES fees(id)
);
CREATE TABLE IF NOT EXISTS repayments (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, loan_id BIGINT NOT NULL, reference VARCHAR(60) NOT NULL UNIQUE,
 amount DECIMAL(19,4) NOT NULL, allocated_to_fees DECIMAL(19,4) NOT NULL, allocated_to_principal DECIMAL(19,4) NOT NULL,
 paid_at TIMESTAMP NOT NULL, CONSTRAINT fk_repayments_loan FOREIGN KEY(loan_id) REFERENCES loans(id), CONSTRAINT ck_repayment_amount CHECK(amount > 0)
);
CREATE TABLE IF NOT EXISTS notification_templates (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code VARCHAR(60) NOT NULL UNIQUE, event_type VARCHAR(30) NOT NULL,
 channel VARCHAR(20) NOT NULL, subject_template VARCHAR(200), body_template VARCHAR(1000) NOT NULL, active BOOLEAN NOT NULL
);
CREATE TABLE IF NOT EXISTS notification_rules (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_type VARCHAR(30) NOT NULL, product_id BIGINT,
 customer_segment VARCHAR(40), channel VARCHAR(20) NOT NULL, enabled BOOLEAN NOT NULL,
 CONSTRAINT fk_rules_product FOREIGN KEY(product_id) REFERENCES products(id)
);
CREATE TABLE IF NOT EXISTS notification_logs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id BIGINT NOT NULL, loan_id BIGINT,
 event_type VARCHAR(30) NOT NULL, channel VARCHAR(20) NOT NULL, subject VARCHAR(200), body VARCHAR(1000) NOT NULL,
 status VARCHAR(20) NOT NULL, sent_at TIMESTAMP NOT NULL,
 CONSTRAINT fk_logs_customer FOREIGN KEY(customer_id) REFERENCES customers(id), CONSTRAINT fk_logs_loan FOREIGN KEY(loan_id) REFERENCES loans(id)
);
